version: "3.5"

services:

  main:
    image: gaetanlandreau/pytorch:latest
    build:
      context: .
      dockerfile: Dockerfile.pytorch
      target: torch

    restart: always
    shm_size: '4gb'
    
    command: "tail -f > dev 2&1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    
    working_dir: /root/

    
    volumes:
        
      # Datadrive . 
      - type: bind
        source: /data2/datasets/
        target: /data/