version: "2.3"

services:
  lab:
    image: "gaetanlandreau/ai-deep3d:latest"
    runtime: nvidia
    build: . 
    restart: always
    shm_size: '2gb'
    #env_file:
      #- .env
    environment:
      - AWS_PROFILE=rd
      - NEPTUNE_API_TOKEN

    command: "jupyter-lab --ip=0.0.0.0 --allow-root --no-browser"
    ports:
      - 6843:8888
    working_dir: /root/
    volumes:
      
      - /home/gaetan/PhD/AdaptativeSR/:/root/   # Mount the root folder of the project. 
      - /data1/gaetan/PhD/:/datadrive/          # Datadrive on Athena. 

      - ${HOME}/.aws/config:/root/.aws/config:ro
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro

      - ${HOME}/.jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json

  dev_ai:
    image: "gaetanlandreau/ai-deep3d:latest"
    container_name: dev-dockerai_gaetan
    runtime: nvidia
    build: . 
    restart: always
    shm_size: '2gb'
    tty: true
    environment:
        - AWS_PROFILE=rd
    command : /bin/bash
    working_dir: /root/
    volumes:
          
      - /home/gaetan/PhD/AdaptativeSR/:/root/   # Mount the root folder of the project. 
      - /data1/gaetan/PhD/:/datadrive/          # Datadrive on Athena. 
      
      - ${HOME}/.aws/config:/root/.aws/config:ro
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
      - ${HOME}/.jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json
