version: "3.5"

services:
  lab:
    image: "gaetanlandreau/pytorch3d:v0.0.1"
    runtime: nvidia
    build: . 
    restart: always
    shm_size: '2gb'
    env_file:
      - .env
    command: "jupyter-lab --ip=0.0.0.0 --allow-root --no-browser"  
    ports:
      - 6843:8888
    working_dir: /root/

    volumes:

      # AWS credentials. 
      - type: bind
        source: /home/gaetan/.aws/
        target: /root/.aws

      #ssh Key
      - type: bind
        source: /home/gaetan/.ssh/
        target: /root/.ssh/
       
      # Datadrive on Athena. 
      - type: bind
        source: /data1/gaetan/PhD/
        target: /data/

      # Mount the root folder of the project. 
      - type: bind
        source: /home/gaetan/PhD/AdaptativeSR/
        target: /root/

  mlflow:
    build: 
      context: . 
      dockerfile: Dockerfile.mlflow
        
    image: "gaetanlandreau/mlflow:latest"
    container_name: mlflow-tracking
    env_file:
      - .env
    links: 
      - lab:lab 
 
    command: "mlflow server -h 0.0.0.0 --backend-store-uri /mlruns_backend/ --default-artifact-root ${ML_ARTIFACT_S3_PATH}"  
    ports:
      - 5000:5000    

    volumes:
     
      # AWS credentials. 
      - type: bind
        source: /home/gaetan/.aws/
        target: /root/.aws
      
      # Datadrive backend saving on Athena. 
      - type: bind
        source: /data1/gaetan/PhD/mlruns_backend/
        target: /mlruns_backend/ 

secrets: 
  ssh_key:
    file: /home/gaetan/.ssh/id_rsa
